@startuml Classdiagram
skinparam ClassAttributeIconSize 0
skinparam Monochrome true
hide circle
class PoisonPotion {
    + PoisonPotion(name:string, level:int)
    + <<override>> Use(target:Character) : void
    + <<override>> GetInfo() : void
}
Item <|-- PoisonPotion
@enduml
