@startuml Classdiagram
skinparam ClassAttributeIconSize 0
skinparam Monochrome true
hide circle

class StartMenu {
    + Start() : void
    RunStartMenu() : void
    + QuitGame() : void
    AboutGame() : void
    StartGame() : void
}
StartMenu o-> "hero" Hero
StartMenu o-> "enemy" Demon
@enduml
